### PR TITLE
Add bio for NickSchaf

### PR DESCRIPTION
**Pull request by NickSchaf**
Adds a bio for @NickSchaf.  Request #20

### CODE REVIEW

**Comment by NickSchaf** [comment]
Closes #20

**Comment by therealjumbo** [comment]
Looks good to me @NickSchaf do you want to bold the items or do you like the italics?

**Comment by NickSchaf** [comment]
https://github.com/githubteacher/developers-09-24-2015/pull/39#issuecomment-142971721
@therealjumbo: Will do both.

**Comment by NickSchaf** [comment]
:shipit:

**Pull request merged**
